using JetBrains.Annotations;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Unity.Netcode;
using Unity.Services.Authentication;
using Unity.Services.Core;
using Unity.Services.Relay;
using Unity.Services.Relay.Models;
using Unity.Netcode.Transports.UTP;
using Unity.Services.Lobbies;
using Unity.Services.Lobbies.Models;
using System;
using System.Collections.Concurrent;
using WebSocketSharp;
public class NetworkConnect : MonoBehaviour
{
    /// <summary>
    /// joinCode generated by Relay, can connect via joinCode if not using Lobbies already.
    /// </summary>
    public string manualJoinCode;

    /// <summary>
    /// Sets max allowed other connections to host
    /// </summary>
    public int maxConnections = 2;
    public UnityTransport transportProtocol;

    private Lobby currentLobby;
    

    private async void Awake(){
        await UnityServices.InitializeAsync();
        await AuthenticationService.Instance.SignInAnonymouslyAsync();
    }
    /// <summary>
    /// creates a local host session for the player
    /// </summary>
    public async void Create()
    {
        Allocation allocation = await RelayService.Instance.CreateAllocationAsync(maxConnections);
        string newJoinCode = await RelayService.Instance.GetJoinCodeAsync(allocation.AllocationId);
        manualJoinCode = newJoinCode;
      
        //transport service setup
        transportProtocol.SetHostRelayData(allocation.RelayServer.IpV4, (ushort)allocation.RelayServer.Port,
        allocation.AllocationIdBytes, allocation.Key, allocation.ConnectionData);

        //Unity lobby setup
        CreateLobbyOptions lobbyOptions = new CreateLobbyOptions();  
        lobbyOptions.IsPrivate = false;
        //creates a data structure for lobby info, then saves the relay join code to it for access later.
        lobbyOptions.Data = new Dictionary<string, DataObject>();
    
        DataObject dataObject = new DataObject(DataObject.VisibilityOptions.Public, newJoinCode);
        lobbyOptions.Data.Add("JOIN_CODE", dataObject);


        currentLobby = await LobbyService.Instance.CreateLobbyAsync("MFA Lobby", maxConnections, lobbyOptions);
        //start couroutine to keep the Lobby active, lobbies go inactive for quickjoin after 30 seconds.
        StartCoroutine(HeartbeatLobbyCoroutine(currentLobby.Id, 20));
        
        //add created lobby to list of created Lobbys, to destroy on host quit.

        NetworkManager.Singleton.StartHost();
    }

    /// <summary>
    /// Allows the player to join a hosted Lobby via Relay connection.
    /// </summary>
    public async void Join()
    {       
            string joinCode;
            //Specify a join code for dev purposes, overrides auto join features.
            if(!manualJoinCode.IsNullOrEmpty()){
                joinCode = manualJoinCode;
            }
            //if no join code is specified, try to join current lobby, find one if current lobby doesnt exist
            else{
                try{
                    Debug.Log("No Manual Join code, trying to quickjoin");
                     //searches for first available lobby then gets join code from saved lobby data.
                    currentLobby = await LobbyService.Instance.QuickJoinLobbyAsync();
                    //Access Relay joincode from Lobby data.
                    joinCode = currentLobby.Data["JOIN_CODE"].Value;
                    //tries to get the current join code for a lobby from a previous join session.
                    
                }
                catch{
                    Debug.Log("Quick Join Failed");
                    joinCode = "Fail";
                }   
            }

            JoinAllocation allocation = await RelayService.Instance.JoinAllocationAsync(joinCode);
            transportProtocol.SetClientRelayData(allocation.RelayServer.IpV4, (ushort)allocation.RelayServer.Port,
            allocation.AllocationIdBytes, allocation.Key, allocation.ConnectionData, allocation.HostConnectionData);
            NetworkManager.Singleton.StartClient();      
    }
    /// <summary>
    /// Coroutine to ping a Lobby every interval
    /// </summary>
    /// <param name="lobbyId"> The lobby.Id, as returned by LobbyService.Instance.CreateLobbyAsync </param>
    /// <param name="intervalSeconds"> interval in seconds to heartbeat the server, should be lower than the 30s default lobby active lifetime</param>
    /// <returns></returns>
    IEnumerator HeartbeatLobbyCoroutine(string lobbyId, float intervalSeconds){
        var delay = new WaitForSecondsRealtime(intervalSeconds);
        while(true){
            LobbyService.Instance.SendHeartbeatPingAsync(lobbyId);
            yield return delay;
        }
    }

    private async void OnApplicationQuit(){
        try
        {
            string playerId = AuthenticationService.Instance.PlayerId;
            await LobbyService.Instance.RemovePlayerAsync(currentLobby.Id, playerId);
        }
        catch (LobbyServiceException e)
        {
                    Debug.Log(e);
        }
    }

}
